### ISSUE TITLE
月と分が逆

### ISSUE THREAD

**Issue by YutaroEnomoto** [kimipooh/getAttechedFilefromGmailtoDrive#1]
MMとmmが逆のようです。
https://sites.google.com/site/gasgaidobukku/utilities/formatdate

p.s. 便利な機能、ありがとうございます。

**Comment by kimipooh** [comment]
報告ありがとうございます！
確かに！
https://developers.google.com/apps-script/reference/utilities/utilities#formatDate(Date,String,String)
の Google Developer Document のサンプルとして
`var formattedDate = Utilities.formatDate(new Date(), "GMT", "yyyy-MM-dd'T'HH:mm:ss'Z'");`
って書いてありました！

修正しておきます！
